spring:
  application:
    name: Jhlite110
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
    password: ''
    driver-class-name: org.postgresql.Driver
    username: jhlite110
    url: jdbc:postgresql://localhost:5432/jhlite110
    type: com.zaxxer.hikari.HikariDataSource
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    redis:
      url: redis://localhost:6379
      database: 0
    mongodb:
      database: jhlite110
      uri: mongodb://localhost:27017/jhlite110
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        cache:
          use_second_level_cache: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  task:
    scheduling:
      thread-name-prefix: jhlite110-scheduling-
      pool:
        size: 2
    execution:
      pool:
        keep-alive: 10s
        queue-capacity: 100
        max-size: 16
      thread-name-prefix: jhlite110-task-
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  liquibase:
    change-log: classpath:config/liquibase/master.xml
logging:
  level:
    com:
      mycompany:
        myapp: INFO
kafka:
  producer:
    '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
    '[value.serializer]': org.apache.kafka.common.serialization.StringSerializer
  bootstrap-servers: localhost:9092
  consumer:
    '[value.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
    '[auto':
      offset.reset]: earliest
    '[key.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
    '[group.id]': myapp
  polling:
    timeout: 10000
application:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
mongock:
  migration-scan-package: com.mycompany.myapp
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  info:
    # Git Information
    git:
      mode: full
      enabled: true
    env:
      enabled: true
